name: Deploy Sample Application Backend to EKS
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0'
      id: install

    - name: Configure AWS Credentials 2
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    - name: get caller identity2
      run: |
        aws sts get-caller-identity
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: sample-app-backend-api
        IMAGE_TAG: latest
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: |
        x=$(aws sts get-caller-identity | jq -r '.Account')
        echo $x
        aws sts get-caller-identity | jq -r '.Account'
        aws eks update-kubeconfig --region us-east-1 --name "thrivestack-dev-eks-cluster" && kubectl get nodes
        
    - name: Replace ACCOUNT_ID in deployment YAML
      run: |
        sed -i 's/\${ACCOUNT_ID}/${{ secrets.AWS_ACCOUNT_ID }}/g' deployment.yaml
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
